### ISSUE TITLE
estimatr

### ISSUE THREAD

**Issue by stevennuss** [ryantmoore/ci-exp-essex-2024#1]
Hiya, all --

Is anyone else having trouble installing the estimatr package? I am using a fairly up to date version of R (4.3.2). The DeclareDesign page says anything after 3.5.0 should be fine.

Best,
Steven

**Comment by ryantmoore** [comment]
In case anyone else encounters the same, @stevennuss was able to solve this by turning off the Mac OS setting 'Limit IP Tracking'.
